site_name: 老胡胡说
site_url: https://windyvictor.github.io/jhu-mkdocs
site_author: Victor Hu
theme:
  name: material
  language: zh
  features:
    - navigation.tabs # 顶级索引被作为tab
    - navigation.tabs.sticky # tab始终可见
    - navigation.top # 开启顶部导航栏
nav:
  - Home: index.md
  - About: about.md
  - Reading: reading.md
  - Research:
      - 数学建模经验分享: math-model-exp.md  # 注意这里的缩进
      - 美赛经验分享: MCM-ICM-exp.md
  - Blog: blog.md
